name: golang-pipeline

on:
  workflow_call:
    inputs:
      # pass in environment through manual trigger, if not passed in, default to 'dev'
      env:
        required: true
        type: string
        default: 'dev'
      # working-directory is added to accommodate monorepo.  For multi repo, defaults to '.', current directory
      working-directory:
        required: false
        type: string
        default: '.'
      # JFROG_URL:
      #   required: true
      #   type: string
      #   default: '.'
      # GOLANG_REPOSITORY:
      #   required: true
      #   type: string
      #   default: '.'
      # GOLANG_IMAGE:
      #   required: true
      #   type: string
      #   default: '.'
      # GOLANG_TAG:
      #   required: true
      #   type: string
      #   default: '.'

jobs:
  build:
    runs-on: [self-hosted]
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: remote
          endpoint: tcp://buildkitd-headless:1234

      - name: Login to JFrog 🐸  
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ${{ secrets.JFROG_URL }}
          username: ${{ secrets.JFROG_USER }}
          password: ${{ secrets.JFROG_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          # context: .
          push: true
          tags: ${{ env.JFROG_URL }}/${{ env.GOLANG_REPOSITORY }}/${{ env.GOLANG_IMAGE }}:$env:GITHUB_RUN_NUMBER
